name: CI Pipeline

# Triggers
on:
  push:
    paths:
      - 'code/**'            # Only trigger when files under "code/" change
  workflow_dispatch:         # Allows manual trigger via GitHub UI

jobs:
  build-test-lint:
    name: Build, Test, Lint, Dockerize
    runs-on: ubuntu-latest     # Use your local self-hosted runner

    steps:
      # Step 1: Checkout your repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python (assumes Python project)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install flake8 pytest

      # Step 4: Build your app (using Makefile)
      - name: Build
        run: make build

      # Step 5: Run tests
      - name: Test
        run: make test

      # Step 6: Lint the code
      - name: Lint
        run: make lint

      # Step 7: Docker login (uses secrets)
      - name: Docker Login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      # Step 8: Build Docker image
      - name: Build Docker Image
        run: make docker-build

      # Step 9: Push Docker image
      - name: Docker Push
        run: make docker-push
