name: CI Pipeline

on:
  push:
    paths:
      - 'code/**'            # Only trigger when files under "code/" change
  workflow_dispatch:         # Allows manual trigger via GitHub UI

jobs:
  build-test-lint:
    name: Build, Test, Lint, Dockerize
    runs-on: ubuntu-latest   # Use GitHub-hosted runner

    steps:
      # Step 1: Checkout your repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install flake8 pytest

      - name: Test
        run: |
          echo "PYTHONPATH: $PYTHONPATH"
          python -c "import sys; print(sys.path)"
          make test
        env:
          PYTHONPATH: ${{ github.workspace }}


      # Step 5: Lint the code
      - name: Lint
        run: make lint

      # Step 6: Docker login
      - name: Docker Login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASS }}
        run: echo "$DOCKER_PASS" | docker login -u "$DOCKER_USERE" --password-stdin

      # Step 7: Build Docker image
      - name: Build Docker Image
        run: make docker-build

      # Step 8: Push Docker image
      - name: Docker Push
        run: make docker-push
